Update PixelOS-SUSFS (3).yml

diff --git a/.github/workflows/PixelOS-SUSFS (3).yml b/.github/workflows/PixelOS-SUSFS (3).yml
--- a/.github/workflows/PixelOS-SUSFS (3).yml
+++ b/.github/workflows/PixelOS-SUSFS (3).yml
@@ -1,50 +1,46 @@
 name: Pixel OS SUSFS
 
-
 on:
-
-    workflow_dispatch:
-      inputs:
-        RELEASE_CONFIG:
-          description: 'Upload to Releases'
-          required: true
-          default: false
-          type: boolean
-        KERNEL_SOURCE:
-          description: 'Kernel Source'
-          required: true
-          default: "https://github.com/asgdrgsdsdgfa/android_kernel_oneplus_sm8350.git"
-          type: string
-        KERNEL_SOURCE_BRANCH:
-          description: 'kernel Branch'
-          required: true
-          default: "fourteen-qpr3"
-          type: string
-        KERNEL_DEFCONFIG:
-          description: 'Kernel Config'
-          required: true
-          default: "vendor/lahaina-qgki_defconfig"
-          type: string
-        KERNELSU_CONFIG:
-          description: 'Compile KernelSU'
-          required: true
-          default: true
-          type: boolean          
-        CCACHE_CONFIG:
-          description: 'Use Ccache'
-          required: true
-          default: true
-          type: boolean
-        KERNELSU_TAG:
-          description: 'Choose KernelSU branch or tag'
-          required: false
-          default: "main"
-          type: string
+  workflow_dispatch:
+    inputs:
+      RELEASE_CONFIG:
+        description: 'Upload to Releases'
+        required: true
+        default: false
+        type: boolean
+      KERNEL_SOURCE:
+        description: 'Kernel Source'
+        required: true
+        default: "https://github.com/asgdrgsdsdgfa/android_kernel_oneplus_sm8350.git"
+        type: string
+      KERNEL_SOURCE_BRANCH:
+        description: 'kernel Branch'
+        required: true
+        default: "fourteen-qpr3"
+        type: string
+      KERNEL_DEFCONFIG:
+        description: 'Kernel Config'
+        required: true
+        default: "vendor/lahaina-qgki_defconfig"
+        type: string
+      KERNELSU_CONFIG:
+        description: 'Compile KernelSU'
+        required: true
+        default: true
+        type: boolean          
+      CCACHE_CONFIG:
+        description: 'Use Ccache'
+        required: true
+        default: true
+        type: boolean
+      KERNELSU_TAG:
+        description: 'Choose KernelSU branch or tag'
+        required: false
+        default: "main"
+        type: string
 
 jobs:
-
   build:
-
     runs-on: ubuntu-latest
     env:
       CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
@@ -53,7 +49,6 @@ jobs:
       CCACHE_HARDLINK: "true"
 
     steps:
-
       - uses: actions/checkout@v4
 
       - name: Ccache
@@ -64,25 +59,24 @@ jobs:
 
       - name: Setup Environment
         run: |
-          export CLANG_PATH=~/clang
-          git clone --depth=1 https://github.com/kdrag0n/proton-clang $CLANG_PATH
-          sh -c "$(curl -sSL https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh)"
-          sudo apt install --fix-missing
-          export LLVM_VERSION=13
-          wget https://apt.llvm.org/llvm.sh
-          chmod +x llvm.sh
-          sudo ./llvm.sh $LLVM_VERSION
-          rm ./llvm.sh
-          sudo apt install --fix-missing
-          sudo ln -s --force /usr/bin/clang-$LLVM_VERSION /usr/bin/clang
-          sudo ln -s --force /usr/bin/ld.lld-$LLVM_VERSION /usr/bin/ld.lld
-          sudo ln -s --force /usr/bin/llvm-objdump-$LLVM_VERSION /usr/bin/llvm-objdump
-          sudo ln -s --force /usr/bin/llvm-ar-$LLVM_VERSION /usr/bin/llvm-ar
-          sudo ln -s --force /usr/bin/llvm-nm-$LLVM_VERSION /usr/bin/llvm-nm
-          sudo ln -s --force /usr/bin/llvm-strip-$LLVM_VERSION /usr/bin/llvm-strip
-          sudo ln -s --force /usr/bin/llvm-objcopy-$LLVM_VERSION /usr/bin/llvm-objcopy
-          sudo ln -s --force /usr/bin/llvm-readelf-$LLVM_VERSION /usr/bin/llvm-readelf
-          sudo ln -s --force /usr/bin/clang++-$LLVM_VERSION /usr/bin/clang++
+          sudo apt-get update
+          sudo apt-get install -y \
+            bc \
+            bison \
+            build-essential \
+            ccache \
+            flex \
+            git \
+            libelf-dev \
+            libncurses-dev \
+            libssl-dev \
+            python3 \
+            rsync \
+            unzip \
+            zip
+
+          export CLANG_PATH=$HOME/clang
+          git clone --depth=1 https://github.com/kdrag0n/proton-clang "$CLANG_PATH"
 
       - name: Git kernel
         run: |
@@ -105,23 +99,44 @@ jobs:
           export KERNEL_PATH=$PWD
           export CLANG_PATH=~/clang
           export PATH=${CLANG_PATH}/bin:${PATH}
-          export CLANG_TRIPLE=aarch64-linux-gnu-
           export ARCH=arm64
           export SUBARCH=arm64
           echo "===================Setup Environment Again==================="
           if [ ! -e "$CLANG_PATH/README.md" ]; then
             git clone --depth=1 https://github.com/kdrag0n/proton-clang $CLANG_PATH
           fi
-          sudo apt install --fix-missing
           echo "=========================Make=========================="
-          make O=out CC="ccache clang" CXX="ccache clang++" ARCH=arm64 CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld $KERNEL_DEFCONFIG
+          make O=out \
+            CC="ccache $CLANG_PATH/bin/clang" \
+            CXX="ccache $CLANG_PATH/bin/clang++" \
+            HOSTCC="gcc -B/usr/bin" \
+            HOSTCXX="g++ -B/usr/bin" \
+            HOSTLD="/usr/bin/ld" \
+            ARCH=arm64 \
+            LLVM=1 \
+            LLVM_IAS=1 \
+            "${KERNEL_DEFCONFIG}"
+
+          test -f out/.config
+          echo "Defconfig generated successfully"
+          
           # Disable LTO
           if [[ $(echo "$(awk '/MemTotal/ {print $2}' /proc/meminfo) < 16000000" | bc -l) -eq 1 ]]; then
-              scripts/config --file out/.config -d LTO -d LTO_CLANG -d THINLTO -e LTO_NONE
+            scripts/config --file out/.config -d LTO -d LTO_CLANG -d THINLTO -e LTO_NONE
           fi
-          make O=out CC="ccache clang" CXX="ccache clang++" ARCH=arm64 -j`nproc` CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld 2>&1 | tee kernel.log
 
-      
+          make O=out \
+            CC="ccache $CLANG_PATH/bin/clang" \
+            CXX="ccache $CLANG_PATH/bin/clang++" \
+            HOSTCC="gcc -B/usr/bin" \
+            HOSTCXX="g++ -B/usr/bin" \
+            HOSTLD="/usr/bin/ld" \
+            ARCH=arm64 \
+            LLVM=1 \
+            LLVM_IAS=1 \
+            -j$(nproc) \
+            2>&1 | tee kernel.log
+
       - name: Create Anykernel3 file
         run: |
           cd $GITHUB_WORKSPACE/kernel
@@ -130,9 +145,12 @@ jobs:
           if test -e $KERNEL_PATH/out/arch/arm64/boot/Image && test -d $KERNEL_PATH/AnyKernel3; then
              zip_name="PixelOS-SUSFS-martini-${{ env.TAG_NAME }}.zip"
              cd $KERNEL_PATH/AnyKernel3
-             cp $KERNEL_PATH/out/arch/arm64/boot/Image $KERNEL_PATH/AnyKernel3
+             cp $KERNEL_PATH/out/arch/arm64/boot/Image .
              zip -r ${zip_name} *
-             mv ${zip_name} $KERNEL_PATH/out/arch/arm64/boot
+             mv ${zip_name} $KERNEL_PATH/out/arch/arm64/boot/
+          else
+             echo "❌ Image or AnyKernel3 not found – build failed"
+             exit 1
           fi
 
       - name: Upload Artifact
